openapi: 3.0.0

info:
  title: Castled.io Events API
  description: An API to track events for Castled.io.
  version: 1.0.0
  # Additional details about the API can be added here
  # termsOfService: "https://www.example.com/terms/"
  # contact:
  #   name: API Support
  #   url: "https://www.example.com/support"
  #   email: support@example.com

servers:
  - url: https://api.castled.io/backend
    # Description about the server
    description: The primary production server for Castled.io events API

paths:
  /external/v1/collections/events:
    post:
      summary: Track event
      description: Send event data to the Castled.io service for tracking.
      operationId: trackEvent
      tags:
        - events
      # Additional operation details
      # externalDocs:
      #   description: Find more info here
      #   url: "https://example.com/moreinfo"
      requestBody:
        required: true
        description: Event data to be tracked. # Description for the request body
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        "200":
          description: Event successfully tracked
          content:
            application/json:
              schema:
                type: object
                description: A standard response for successful event tracking. # Description for the response schema
                properties:
                  message:
                    type: string
                    description: Details about the tracking status. # Description for individual property
      parameters:
        - name: App-Id
          in: header
          required: true
          description: Unique identifier for the application. # Description for the parameter
          schema:
            type: string
        - name: Api-Key
          in: header
          required: true
          description: Authentication key to access the API.
          schema:
            type: string

components:
  schemas:
    Event:
      description: Schema representing the event data. # Description for the schema
      type: object
      required:
        - userId
      properties:
        type:
          type: string
          description: The type of event being tracked. # Description for individual property
          example: track
        userId:
          type: string
          description: Email ID of the user triggering the event.
          example: email@domain.com
        event:
          type: string
          description: Name of the event being tracked.
          example: Added to cart
        properties:
          type: object
          description: Additional properties related to the event.
          additionalProperties:
            type: string
        timestamp:
          type: string
          format: date-time
          description: Time when the event took place.
          example: "2012-12-02T00:30:08.276Z"
