openapi: 3.0.0
info:
  title: Castled.io Events API
  description: An API to track events for Castled.io.
  version: 1.0.0
servers:
  - url: https://app.castled.io/backend
paths:
  /external/v1/collections/events:
    post:
      summary: Track an event
      description: Send event data to the Castled.io service for tracking.
      operationId: trackEvent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Event successfully tracked
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
      parameters:
        - name: App-Id
          in: header
          required: true
          schema:
            type: string
        - name: Api-Key
          in: header
          required: true
          schema:
            type: string

components:
  schemas:
    Event:
      type: object
      properties:
        type:
          type: string
          example: track
        userId:
          type: string
          example: email@domain.com
        event:
          type: string
          example: Added to cart
        properties:
          type: object
          additionalProperties:
            type: string
          example:
            customKey1: "property1"
            customKey2: "property2"
        timestamp:
          type: string
          format: date-time
          example: "2012-12-02T00:30:08.276Z"
