openapi: 3.0.0

info:
  title: Castled.io User Identify API
  description: An API to identify users for Castled.
  version: 1.0.0
  # Additional details about the API can be added here
  # termsOfService: "https://www.example.com/terms/"
  # contact:
  #   name: API Support
  #   url: "https://www.example.com/support"
  #   email: support@example.com

servers:
  - url: https://api.castled.io/backend
    # Description about the server
    description: The primary production server for Castled.io events API

paths:
  /external/v1/collections/users:
    post:
      summary: Identify user
      description: Send user data to the Castled.
      operationId: trackUser
      tags:
        - users
      # Additional operation details
      # externalDocs:
      #   description: Find more info here
      #   url: "https://example.com/moreinfo"
      requestBody:
        required: true
        description: User data to be tracked. # Description for the request body
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Event"
      responses:
        "204":
          description: User successfully tracked
      parameters:
        - name: Api-Key
          in: header
          required: true
          description: API generated from Castled dashboard.
          schema:
            type: string

components:
  schemas:
    Event:
      description: Schema representing the user data. # Description for the schema
      type: object
      required:
        - userId
        - properties
      properties:
        userId:
          type: string
          description: Unique id of the user
          example: 1a56624a-1223bc-127283d
        traits:
          type: object
          description: Flatmap for tracking traits associated with the user.
          additionalProperties:
            type: string
